---
title: "wealth_inequality"
author: "Matt Haraden"
date: "2022-10-06"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)

```

```{r}
income <- read_csv("Median_Household_Income (1).csv")
dirty_streets <- read.csv("Dirty_streets.csv")
```

```{r}
diff_income <-income %>%
  select(CSA2010, mhhi10, mhhi20) %>%
    mutate(Diff_Income = (mhhi20-mhhi10)) %>% 
    mutate(Diff_Pct_2020 = (mhhi20-mhhi10)/mhhi10*100) %>% 
    arrange(Diff_Pct_2020)
```

```{r}
diff_streets <-dirty_streets %>%
  select(CSA2010, dirtyst10, dirtyst20) %>%
  mutate(Diff_total_calls = (dirtyst20-dirtyst10)) %>%
    mutate(Diff_Pct_2020 = (dirtyst20-dirtyst10)/dirtyst10*100) %>% 
  arrange(desc(Diff_Pct_2020))
```

```{r}
top5_diff_streets <- diff_streets %>% 
  slice_max(Diff_Pct_2020, n=5)
top5_diff_streets %>% 
  ggplot() +
  geom_bar(aes(x= reorder(CSA2010, Diff_Pct_2020), weight=Diff_Pct_2020)) +
  coord_flip() + 
  theme_minimal()+
    labs(
    title="Largest Increase In Dirty Streets, Baltimore 2010-2020",
    x = "Neighborhood",
    y = "Percent Increase of Dirty Street Calls",
    caption = "source: Baltimore 311 Service Call Data, 2010-2020")
```




